services:
  web:
    build:
      context: .  
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/CNPM  
    working_dir: /CNPM/project/CNPM  
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy  

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Tt@123456
      POSTGRES_DB: DjangoDB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d DjangoDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
