version: '3.8'

services:
  web:
    build:
      context: .  
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/CNPM  
    working_dir: /CNPM/project/CNPM  
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy  
    environment:
      - DATABASE_NAME=DjangoDB
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=Tt@123456
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SETTINGS_MODULE=CNPM.settings  # Thêm dòng này vào để chỉ định tệp settings
    networks:
      - cnpm_network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Tt@123456
      POSTGRES_DB: DjangoDB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d DjangoDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cnpm_network

volumes:
  db_data:

networks:
  cnpm_network:
