# Generated by Django 5.1.5 on 2025-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ManyToManyField(related_name='customers', to='app.category'),
        ),
    ]
