# Generated by Django 5.1.5 on 2025-02-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thu_cung', models.CharField(max_length=100)),
                ('chu_so_huu', models.CharField(max_length=100)),
                ('trang_thai', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LichKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thu_cung', models.CharField(max_length=100)),
                ('ten_bac_si', models.CharField(max_length=100)),
                ('thoi_gian', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong', models.CharField(max_length=100)),
                ('loai_phong', models.CharField(max_length=50)),
                ('suc_chua', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('loai', models.CharField(max_length=50)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nhan_Vien.phong')),
            ],
        ),
    ]
