# Generated by Django 5.1.4 on 2025-02-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('schedule_time', models.DateTimeField()),
                ('room', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PetHospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('cage_number', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('under_treatment', 'Under Treatment'), ('discharged', 'Discharged')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=50)),
            ],
        ),
    ]
