# Generated by Django 5.1.4 on 2024-12-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('RR', 'Room Regular'), ('DB', 'Deluxe Room'), ('TC', 'Tiny Cage')], max_length=2)),
                ('status', models.CharField(default='Available', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
