# Generated by Django 5.1.4 on 2025-02-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_gender', models.CharField(choices=[('male', 'Đực'), ('female', 'Cái')], max_length=10)),
                ('pet_condition', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thu_cung', to='KhachHang.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('doctor_name', models.CharField(blank=True, choices=[('Triệu Hoàng Nam', 'Bác sĩ Triệu Hoàng Nam'), ('Phạm Thảo', 'Tiến sĩ Phạm Thảo'), ('Nguyễn Văn Hùng', 'Bác sĩ Nguyễn Văn Hùng'), ('Võ Hùng', 'Bác sĩ Võ Hùng'), ('Bùi Minh Tân', 'Bác sĩ Bùi Minh Tân'), ('Võ Hạnh Nhi', 'Bác sĩ Võ Hạnh Nhi')], max_length=255, null=True)),
                ('staff_notes', models.TextField(blank=True, null=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhachHang.khachhang')),
                ('thu_cung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhachHang.thucung')),
            ],
        ),
    ]
