# Generated by Django 5.1.4 on 2025-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_gender', models.CharField(choices=[('Male', 'Đực'), ('Female', 'Cái')], max_length=10)),
                ('pet_condition', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('doctor_choice', models.CharField(choices=[('Bác sĩ Triệu Hoàng Nam', 'Bác sĩ Triệu Hoàng Nam'), ('Tiến sĩ Nguyễn Văn A', 'Tiến sĩ Nguyễn Văn A'), ('Bác sĩ Nguyễn Văn Hùng', 'Bác sĩ Nguyễn Văn Hùng'), ('Bác sĩ Võ Hùng', 'Bác sĩ Võ Hùng')], max_length=255)),
            ],
        ),
    ]
