# Generated by Django 5.1.4 on 2025-02-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhen',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='lichhen',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KhachHang.bacsi'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='thu_cung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KhachHang.thucung'),
        ),
    ]
