# Generated by Django 5.1.4 on 2025-02-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0002_remove_lichhen_doctor_name_lichhen_bac_si_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacsi',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='address',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='staff_notes',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='pet_condition',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='pet_gender',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='pet_name',
        ),
        migrations.AddField(
            model_name='bacsi',
            name='ten',
            field=models.CharField(blank=True, default='Tên bác sĩ', max_length=100),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='ten',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='da_huy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='da_thanh_toan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='ly_do_huy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='ngay_hen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='ngay_huy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='phi_kham',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='thoi_gian_hen',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thucung',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KhachHang.khachhang'),
        ),
        migrations.AddField(
            model_name='thucung',
            name='loai',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='thucung',
            name='ten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='thucung',
            name='tuoi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='bac_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KhachHang.bacsi'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KhachHang.khachhang'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='thu_cung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KhachHang.thucung'),
        ),
    ]
