# Generated by Django 5.1.4 on 2025-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0002_alter_appointment_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
