# Generated by Django 5.1.4 on 2025-02-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0002_bacsi_khachhang_lichhen_thucung_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lichhen',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
