# Generated by Django 5.1.4 on 2025-02-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0003_remove_bacsi_doctor_name_remove_khachhang_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lichhen',
            old_name='thoi_gian_hen',
            new_name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='so_dien_thoai',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='da_huy',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='da_thanh_toan',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='ly_do_huy',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='ngay_hen',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='ngay_huy',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='phi_kham',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='khach_hang',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='loai',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='thucung',
            name='tuoi',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thucung',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thu_cung', to='KhachHang.khachhang'),
        ),
        migrations.AddField(
            model_name='thucung',
            name='pet_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thucung',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('male', 'Đực'), ('female', 'Cái')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='thucung',
            name='pet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bacsi',
            name='ten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='bac_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KhachHang.bacsi'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='thu_cung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KhachHang.thucung'),
        ),
    ]
