# Generated by Django 5.1.4 on 2025-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0005_appointment_diagnosis_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
