# Generated by Django 5.1.4 on 2025-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0006_appointment_fee_amount_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
