# Generated by Django 5.1.4 on 2025-02-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bacsi', '0002_remove_medicalrecord_patient_name_and_more'),
        ('Nhanvien', '0003_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='Nhanvien.booking'),
        ),
    ]
