# Generated by Django 5.1.4 on 2025-02-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bacsi', '0001_initial'),
        ('Nhanvien', '0003_alter_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='progress',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nhanvien.booking'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
