# Generated by Django 5.1.4 on 2025-02-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bacsi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='species',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(default='Chưa có chẩn đoán'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_name',
            field=models.CharField(default='Chưa có tên', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='progress',
            field=models.CharField(max_length=100),
        ),
    ]
