# Generated by Django 5.1.4 on 2025-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bacsi', '0003_alter_medicalrecord_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('NHAP_VIEN', 'Nhập viện'), ('XUAT_VIEN', 'Xuất viện'), ('DIEU_TRI', 'Đang điều trị')], default='DIEU_TRI', max_length=20),
        ),
    ]
