# Generated by Django 5.1.4 on 2025-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bacsi', '0004_medicalrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='cage_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
