# Generated by Django 5.1.4 on 2025-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nhanvien', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='pethospitalization',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pethospitalization',
            name='cage_number',
        ),
        migrations.RemoveField(
            model_name='pethospitalization',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='pethospitalization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pethospitalization',
            name='diagnosis',
            field=models.TextField(default='Unknown diagnosis'),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='A001', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pethospitalization',
            name='admission_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pethospitalization',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
    ]
