# Generated by Django 5.1.4 on 2025-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nhanvien', '0006_booking_cage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
