# Generated by Django 5.1.4 on 2025-02-16 15:47

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_systemconfig_remove_revenue_revenue_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('chuyen_mon', models.CharField(max_length=100)),
                ('gioi_thieu', models.TextField()),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CauHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('gia_tri', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChungCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_chuong', models.CharField(max_length=100, unique=True)),
                ('loai_chuong', models.CharField(max_length=100)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoanhThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateField()),
                ('doanh_thu_ngay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doanh_thu_tuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doanh_thu_thang', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='veterinarian',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='khach_hang',
            field=models.ForeignKey(default=home.models.some_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='ngay_dang_ky',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='thanh_toan_truoc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trang_thai',
            field=models.CharField(choices=[('Đang Chờ', 'Đang Chờ'), ('Đã Xác Nhận', 'Đã Xác Nhận'), ('Đã Hủy', 'Đã Hủy')], default='Đang Chờ', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='bac_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bacsi'),
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_tai_khoan', models.CharField(choices=[('Khách Hàng', 'Khách Hàng'), ('Nhân Viên', 'Nhân Viên'), ('Admin', 'Admin'), ('Bác Sĩ', 'Bác Sĩ')], max_length=50)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThuCung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('loai', models.CharField(max_length=100)),
                ('tuoi', models.IntegerField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoSoKhamBenh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateTimeField()),
                ('chuan_doan', models.TextField()),
                ('dieu_tri', models.TextField()),
                ('danh_gia', models.IntegerField(blank=True, choices=[(1, 'Rất Tệ'), (2, 'Tệ'), (3, 'Bình Thường'), (4, 'Tốt'), (5, 'Rất Tốt')], null=True)),
                ('thu_cung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.thucung')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='thu_cung',
            field=models.ForeignKey(default=home.models.some_default_thu_cung, on_delete=django.db.models.deletion.CASCADE, to='home.thucung'),
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
    ]
